name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: 'Build Inventory Image'
      run: |
        export TIMESTAMP=$(date +%s)
        docker build . --tag ghcr.io/sethjones/kube-rclone:latest
        docker tag ghcr.io/sethjones/kube-rclone:latest ghcr.io/sethjones/kube-rclone:$TIMESTAMP
        docker push ghcr.io/sethjones/kube-rclone:$TIMESTAMP
        docker push ghcr.io/sethjones/kube-rclone:latest
        
